#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 12
#SBATCH --partition studentq
#SBATCH --time 24:00:00

export SCM_TMPDIR=/local/datastore0/$USER/$SLURM_JOBID
srun mkdir -p $SCM_TMPDIR
chmod 700 $SCM_TMPDIR
cd $SCM_TMPDIR
export TC_SUBMISSION_DIR=$SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST >> $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.$SLURM_JOBID.out

$ADFBIN/adf <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

XC
  GGA BP86
END

BASIS
  TYPE TZ2P
  CORE none
END

ANALYTICALFREQ
END

SCF
  iterations 250
END

Geometry
  Iterations 300
  Optim Cartesian
  Convergence E=1e-4 grad=1e-4
End

SYMMETRY nosym
CHARGE -1

ZLMFIT
  Quality normal
END

BECKEGRID
  Quality good
End

ATOMS
N      -2.00553415      -1.79740498       0.38699193
H      -1.72459619      -2.79032961       0.55171634
H      -2.46096439      -1.41658868       1.24694805
H      -2.67738763      -1.75324308      -0.41214729
B      -0.77651738      -0.97276930       0.05937878
H      -1.09006645       0.16252664      -0.12864211
H      -0.00451945      -1.01989304       0.96737911
H      -0.25222673      -1.40132182      -0.92253458
END

ENDINPUT
eor

cp TAPE21 $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.t21
