#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 12
#SBATCH --partition studentq
#SBATCH --time 24:00:00

export SCM_TMPDIR=/local/datastore0/$USER/$SLURM_JOBID
srun mkdir -p $SCM_TMPDIR
chmod 700 $SCM_TMPDIR
cd $SCM_TMPDIR
export TC_SUBMISSION_DIR=$SLURM_SUBMIT_DIR

$ADFBIN/adf <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

XC
    GGA BLYP
END

BASIS
    TYPE TZ2P
    CORE none
END

FRAGMENTS
1 /home/tcst25/advanced_comp_chemistry/exercise3/deel2/AlCO6/sp/sp_AlCO5.t21
2 /home/tcst25/advanced_comp_chemistry/exercise3/deel2/AlCO6/sp/sp_CO.t21
END

SCF
    iterations 250
END

EPRINT
    SFO Eig Ovl
END

ZLMFIT
    Quality normal
END

BECKEGRID
    Quality good
End

REMOVEFRAGORBITALS
 1
    E1:1 62
    E1:2 62
 SUBEND

 2
  B1 4
  B2 4
  E1:1 11
  E1:2 11
 SUBEND
END

SYMMETRY C(4V)
CHARGE +3

ATOMS
    1.Al        0.000000    0.000000    0.000000 f=1
    2.C         0.000000    2.225999    0.000000 f=1
    3.O         0.000000    3.348199    0.000000 f=1
    4.C         0.000000    0.000000    2.225999 f=2
    5.O         0.000000    0.000000    3.348199 f=2
    6.C         0.000000   -2.225999    0.000000 f=1
    7.O         0.000000   -3.348199    0.000000 f=1
    8.C         0.000000    0.000000   -2.225999 f=1
    9.O         0.000000    0.000000   -3.348199 f=1
   10.C         2.225999    0.000000    0.000000 f=1
   11.O         3.348199    0.000000    0.000000 f=1
   12.C        -2.225999    0.000000    0.000000 f=1
   13.O        -3.348199    0.000000    0.000000 f=1
END

ENDINPUT
eor

cp TAPE21 $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.t21
