#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 12
#SBATCH --partition studentq
#SBATCH --time 24:00:00

export SCM_TMPDIR=/local/datastore0/$USER/$SLURM_JOBID
srun mkdir -p $SCM_TMPDIR
chmod 700 $SCM_TMPDIR
cd $SCM_TMPDIR
export TC_SUBMISSION_DIR=$SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST >> $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.$SLURM_JOBID.out

$ADFBIN/adf <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

XC
  GGA BP86
END

BASIS
  TYPE TZ2P
  CORE none
END

ANALYTICALFREQ
END

SCF
  iterations 250
END

Geometry
  Iterations 300
  Optim Cartesian
  Convergence E=1e-4 grad=1e-4
End

SYMMETRY nosym
CHARGE 0

ZLMFIT
  Quality normal
END

BECKEGRID
  Quality good
End

ATOMS
B       0.75102400      -2.09420619       1.36527081
Cl       1.74296291      -2.17080488      -0.15194850
Cl       1.00873660      -0.74306337       2.54838488
Cl      -0.58558193      -3.29114040       1.63470678
END

ENDINPUT
eor

cp TAPE21 $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.t21