#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 12
#SBATCH --partition studentq
#SBATCH --time 24:00:00

export SCM_TMPDIR=/local/datastore0/$USER/$SLURM_JOBID
srun mkdir -p $SCM_TMPDIR
chmod 700 $SCM_TMPDIR
cd $SCM_TMPDIR
export TC_SUBMISSION_DIR=$SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST >> $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.$SLURM_JOBID.out

$ADFBIN/adf <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

XC
  GGA blyp
  DISPERSION Grimme3 BJDAMP
END

BASIS
  TYPE TZ2P
  CORE none
END

ANALYTICALFREQ
END

SCF
  iterations 250
END

Geometry
  Iterations 300
  Optim Cartesian
  Convergence E=1e-4 grad=1e-4
End

SYMMETRY nosym
CHARGE -1

ZLMFIT
  Quality normal
END

BECKEGRID
  Quality good
End

ATOMS
Br     -4.94867129       3.04098476       0.02199102
Cl     -3.76372578       1.14672480       0.05741844
Br    -6.06298381       5.11120939      -0.21661069
END

ENDINPUT
eor

cp TAPE21 $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.t21