#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 12
#SBATCH --partition studentq
#SBATCH --time 24:00:00

export SCM_TMPDIR=/local/datastore0/$USER/$SLURM_JOBID
srun mkdir -p $SCM_TMPDIR
chmod 700 $SCM_TMPDIR
cd $SCM_TMPDIR
export TC_SUBMISSION_DIR=$SLURM_SUBMIT_DIR

$ADFBIN/adf <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

XC
    GGA BLYP
END

BASIS
    TYPE TZ2P
    CORE none
END

FRAGMENTS
1 $SLURM_SUBMIT_DIR/sp_meth1_frag1_FeCO4.t21
2 $SLURM_SUBMIT_DIR/sp_meth1_frag2_CO.t21
END

SCF
    iterations 250
END

EPRINT
    SFO Eig Ovl   
END

ZLMFIT
    Quality normal
END

BECKEGRID
    Quality good
End

SYMMETRY C(3V)
CHARGE 0

ATOMS
    1.Fe        0.000000    0.000000    0.000000 f=1
    2.C         0.917397    1.588977    0.000000 f=1
    3.O         1.495217    2.589792    0.000000 f=1
    4.C         0.917397   -1.588977    0.000000 f=1
    5.O         1.495217   -2.589792    0.000000 f=1
    6.C         0.000000    0.000000    1.835389 f=2
    7.O         0.000000    0.000000    2.987899 f=2
    8.C         0.000000    0.000000   -1.835389 f=1
    9.O         0.000000    0.000000   -2.987899 f=1
   10.C        -1.834793    0.000000    0.000000 f=1
   11.O        -2.990435    0.000000    0.000000 f=1
END

ENDINPUT
eor

cp TAPE21 $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.t21
