#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 12
#SBATCH --partition studentq
#SBATCH --time 24:00:00

export SCM_TMPDIR=/local/datastore0/$USER/$SLURM_JOBID
srun mkdir -p $SCM_TMPDIR
chmod 700 $SCM_TMPDIR
cd $SCM_TMPDIR
export TC_SUBMISSION_DIR=$SLURM_SUBMIT_DIR
echo $SLURM_JOB_NODELIST >> $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.$SLURM_JOBID.out

$ADFBIN/adf <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

XC
  GGA BP86
END

BASIS
  TYPE TZ2P
  CORE none
END

ANALYTICALFREQ
END

SCF
  iterations 250
END

Geometry
  Iterations 300
  Optim Cartesian
  Convergence E=1e-4 grad=1e-4
End

SYMMETRY nosym
CHARGE 0

ZLMFIT
  Quality normal
END

BECKEGRID
  Quality good
End

ATOMS
B      -1.93674973      -0.19660619      -1.00157324
Br      -1.34041538       1.00771287      -2.44656142
Br      -2.03130429      -2.13963400      -1.33335815
Br      -2.02610730       0.47778466       0.85090899
H       2.15216324       0.08643139      -0.38379873
N       1.44915214      -0.68382245      -0.32903645
H       1.73969307      -1.40733441      -1.02376003
H       1.54798870      -1.11624195       0.61652965
END

ENDINPUT
eor

cp TAPE21 $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.t21
